-- SPDX-License-Identifier: GPL-3.0-or-later
-- DFPlayerButton.lua - the player panel's badge in the vanilla left sidebar,
-- hung beneath every Dragonfly mark above it (client only).
--
-- THE COLOR SCHEME IS THE OWNER'S, AND IT IS NOT THE ADMIN ONE: blue mark =
-- panel CLOSED, red mark = panel OPEN. The admin surfaces speak green/red;
-- the player surface got its own Off master (the green leaf-vein gradient
-- rotated to teal-blue-indigo, art/dragonfly/DF_PlayerPanel_Off_master.png)
-- exactly so the two doors can never be mistaken for one another, and so
-- staff - who see every badge in the column - always know which panel a
-- click opens. The red On master is SHARED with the admin badge art; only
-- Off diverges. Unlike DFDeckButton's deliberate incubation inversion, these
-- are worn honestly: Off art when closed, On art when open, nothing to swap
-- back later.
--
-- ART SHIPS BESIDE THE ADMIN SET (media/ui/DFSidebar/<W>/DF_PlayerPanel_*,
-- generated by tools/make-sidebar-icon.py from the masters, --align-with
-- pairing them so the state swap does not jump). The DF_PlayerPanel_ name
-- keeps it distinct from the admin badge's DF_Panel_ files sharing the same
-- folders. If the art is missing the text badge ("PANEL") keeps the button
-- working.
--
-- MECHANISM: the same two-wrap ISEquippedItem patch the deck badge uses -
-- initialise creates + shrinkWrap, prerender anchors + reflects state; see
-- DFDeckButton's header for the full why (it inherited the canonical
-- documentation when DFSideButton retired at graduation). Alphabetical file
-- order makes our wraps run AFTER DFDeckButton's, so the deck badge is
-- already anchored this frame by the time we sit beneath it.
--
-- VISIBLE TO EVERYONE - this is the ungated door to an ungated surface. The
-- anchor chain still ends at the vanilla trio, which exists in MP; in solo
-- the sidebar has no anchor for us and the badge stays hidden, which is the
-- known limit of this entry idiom (the admin badges share it). A solo entry
-- point is an open question for the owner, alongside the keybind.
--
-- RELOAD-SAFE: wraps install once behind a surviving sentinel; re-running
-- this file must never stack a second wrap chain onto ISEquippedItem.

if isServer() then return end
if not ISEquippedItem then return end

require "DFPlayerDeck"

DFPlayerButton = DFPlayerButton or {}

DFPlayerBtnState = DFPlayerBtnState or { wrapped = false }

local SPACING = 10
local SIZE_BUCKETS = { 48, 64, 80, 96, 128 }

local iconCache = {}   -- bucket -> { off = tex, on = tex } | false

local function tex(path)
    -- the getTexture GLOBAL is self-catching (LuaManager:6855 ->
    -- Texture.getSharedTexture:406, try/catch returning null), so a missing
    -- file is a nil here, never a throw
    return getTexture(path)
end

local function bucketFor(width)
    local best, bestDiff = SIZE_BUCKETS[#SIZE_BUCKETS], nil
    for _, b in ipairs(SIZE_BUCKETS) do
        local d = math.abs(b - (width or 0))
        if not bestDiff or d < bestDiff then best, bestDiff = b, d end
    end
    return best
end

local function resolveIcon(width)
    local b = bucketFor(width)
    local hit = iconCache[b]
    if hit ~= nil then return hit or nil end

    local off = tex("media/ui/DFSidebar/" .. b .. "/DF_PlayerPanel_Off_" .. b .. ".png")
    local on  = off and tex("media/ui/DFSidebar/" .. b .. "/DF_PlayerPanel_On_" .. b .. ".png") or nil

    if not off or not on then
        iconCache[b] = false
        return nil
    end
    iconCache[b] = { off = off, on = on }
    return iconCache[b]
end

local function panelOpen()
    return DFPlayerDeckState ~= nil and DFPlayerDeckState.instance ~= nil
       and DFPlayerDeckState.instance.getIsVisible ~= nil
       and DFPlayerDeckState.instance:getIsVisible()
end

local function onClick()
    if DFPlayerDeck and DFPlayerDeck.toggle then DFPlayerDeck.toggle() end
end

if not DFPlayerBtnState.wrapped then
    DFPlayerBtnState.wrapped = true

    local _origInitialise = ISEquippedItem.initialise
    function ISEquippedItem:initialise()
        _origInitialise(self)
        if not self.adminBtn then return end

        if self.dfPlayerBtn then
            -- Vanilla removeChild is nil-safe if a previous UI backing object
            -- has already been torn down (ISUIElement.lua:1480-1485).
            self:removeChild(self.dfPlayerBtn)
            self.dfPlayerBtn = nil
        end

        local w = self.adminBtn:getWidth()
        local h = self.adminBtn:getHeight()
        local icon = resolveIcon(w)
        self.dfPlayerIcon = icon

        local btn = ISButton:new(self.adminBtn:getX(), self.adminBtn:getBottom() + SPACING,
                                 w, h, icon and "" or "PANEL", self, onClick)
        btn.internal = "DFPLAYERPANEL"
        btn:initialise()
        btn:instantiate()
        btn:ignoreWidthChange()
        btn:ignoreHeightChange()

        if icon then
            btn:setImage(icon.off)
            btn:setDisplayBackground(false)
            btn.borderColor = { r = 1, g = 1, b = 1, a = 0.1 }
        else
            -- Fallback chrome in this surface's tide blue, matching the art
            -- it stands in for.
            btn:setDisplayBackground(true)
            btn.backgroundColor          = { r = 0.03, g = 0.04, b = 0.04, a = 0.85 }
            btn.backgroundColorMouseOver = { r = 0.08, g = 0.12, b = 0.14, a = 0.95 }
            btn.borderColor              = { r = 0.20, g = 0.73, b = 0.89, a = 0.60 }
        end

        btn:setTooltip("Dragonfly Player Panel")
        self:addChild(btn)
        self.dfPlayerBtn = btn
        self:shrinkWrap()
    end

    local _origPrerender = ISEquippedItem.prerender
    function ISEquippedItem:prerender()
        _origPrerender(self)   -- the badges above us anchor in here

        local btn = self.dfPlayerBtn
        if not btn then return end

        -- Beneath the bottom-most badge standing: the deck's, then the
        -- vanilla trio. All of those are staff-gated or context-dependent,
        -- so for most players the anchor is simply the trio.
        local bottom = nil
        for _, ref in ipairs({ self.clientBtn, self.adminBtn, self.warManagerBtn,
                               self.dfDeckBtn }) do
            if ref and ref:isVisible() then
                local b = ref:getBottom()
                if not bottom or b > bottom then bottom = b end
            end
        end
        if not bottom then
            btn:setVisible(false)
            return
        end
        btn:setVisible(true)

        local targetY = bottom + SPACING
        if btn:getY() ~= targetY then btn:setY(targetY) end

        local icon = self.dfPlayerIcon
        if icon then
            -- Honest colors: blue closed, red open.
            btn:setImage(panelOpen() and icon.on or icon.off)
        end

        if btn:getBottom() > self:getHeight() then
            self:setHeight(btn:getBottom())
        end
    end
end

return DFPlayerButton

-- ---------------------------------------------------------------------------
-- Copyright (C) 2026 Project_Omen. Part of Requiem of the Dead.
--
-- Free software under the GNU General Public License, version 3 or later.
-- You may use, study, modify and share it. If you share it - modified or not,
-- on the Workshop or anywhere else - keep this notice, license your version
-- under the GPL too, publish your source, and say what you changed.
-- Distributed in the hope it is useful, but WITHOUT ANY WARRANTY.
-- <https://www.gnu.org/licenses/gpl-3.0.html>
