-- SPDX-License-Identifier: GPL-3.0-or-later
-- BBLibrary_BanList.lua - bundled ban list for the RFTDBanBox engine.
--
-- This is the BBLibrary submod: the opinionated ban list (the Requiem of the Dead
-- server's defaults) that used to ship inside Dragonfly itself. It is now OPT-IN -
-- enable the "BBLibrary" mod in your server's mod list to apply it; leave it
-- disabled to run the BanBox engine with no built-in bans.
--
-- Server owners: do NOT edit this file to add your own bans - a Workshop update
-- overwrites it. Copy BBLibrary_Example.lua into your own mod instead.
--
-- Depends on RFTDBanBox, which is where the engine lives and what mod.info
-- declares. The engine moved out of Dragonfly at the Core migration; the DF*
-- prefix on DFBanBox is a frozen identifier, not a statement about ownership.
-- `require "DFBanBox"` below forces the engine to load first regardless of mod
-- order.

require "DFBanBox"

DFBanBox.ban("Base.Yoyo")


-- Server-specific player notice (policy, not engine mechanism): overrides the
-- engine's generic default with this server's wording + ticket process. %s = item name.
DFBanBox.removalMessage =
    "%s has been removed from your inventory. If you feel this is in error please submit a discord ticket with the current time."

-- ---------------------------------------------------------------------------
-- Copyright (C) 2026 Project_Omen. Part of Requiem of the Dead.
--
-- Free software under the GNU General Public License, version 3 or later.
-- You may use, study, modify and share it. If you share it - modified or not,
-- on the Workshop or anywhere else - keep this notice, license your version
-- under the GPL too, publish your source, and say what you changed.
-- Distributed in the hope it is useful, but WITHOUT ANY WARRANTY.
-- <https://www.gnu.org/licenses/gpl-3.0.html>
