-- BBLibrary_BanList.lua — bundled ban list for Dragonfly's BanBox engine.
--
-- This is the BBLibrary submod: the opinionated ban list (the Requiem of the Dead
-- server's defaults) that used to ship inside Dragonfly itself. It is now OPT-IN —
-- enable the "BBLibrary" mod in your server's mod list to apply it; leave it
-- disabled to run the BanBox engine with no built-in bans.
--
-- It attaches to Dragonfly's BanBox engine through the public API. `require`
-- forces the engine to load first, so mod load order doesn't matter.
--
-- Server owners: do NOT edit this file to add your own bans — a Workshop update
-- overwrites it. Copy BBLibrary_Example.lua into your own mod instead.
--
-- Depends on Dragonfly (the BanBox engine lives there); mod.info declares
-- `require=Dragonfly`. `require "DFBanBox"` below also forces the engine to load
-- first regardless of mod order.

require "DFBanBox"

DFBanBox.ban("Base.Yoyo")
DFBanBox.ban("LD.LDMagLegendary")
DFBanBox.ban("LF.LFMagLegendary")
DFBanBox.ban("LTW.LTWMag")
DFBanBox.ban("LK.LKMagLegendary")
DFBanBox.ban("LB.LBMagLegendary")
DFBanBox.ban("Phun.WristWatch_Left_MilitaryX")

-- Server-specific player notice (policy, not engine mechanism): overrides the
-- engine's generic default with this server's wording + ticket process. %s = item name.
DFBanBox.removalMessage =
    "%s has been removed from your inventory. If you feel this is in error please submit a discord ticket with the current time."
