-- SPDX-License-Identifier: GPL-3.0-or-later
-- BBLibrary_Example.lua - TEMPLATE for building your own ban list (your BBL).
--
-- This file does NOTHING on its own: every line below is commented out. It is a
-- copy-paste reference, not an active list. To ban your own items:
--
--   1. Create your own server-side mod (or reuse one you already maintain).
--   2. Drop a file like this into its  media/lua/server/  folder.
--   3. require the engine, then call DFBanBox.ban() once per item using the
--      item's FULL type (Module.Type). Find an item's full type with the
--      debug-menu item picker, or read it from the item mod's scripts.
--   4. Bans take effect on the next server restart - the engine strips them from
--      the loot distribution before any container fills. Prevention only:
--      copies already placed in the world are left alone.
--
-- You do NOT need the BBLibrary submod enabled to use the engine. BBLibrary is
-- just a ready-made list; your own list mod needs RFTDBanBox (the engine), not
-- BBLibrary. RFTDBanBox is a separately enableable mod id, NOT something that is
-- always present - declare `require=RFTDBanBox` in your mod.info and
-- `require "DFBanBox"` in your Lua, or your ban calls hit a nil engine.
--
-- Master toggle: SandboxVars.RFTDBanBox.BanBoxEnabled (default ON) gates the
-- whole engine, so a server can pause all banning without disabling mods.

-- require "DFBanBox"
--
-- DFBanBox.ban("Base.Yoyo")
-- DFBanBox.ban("YourMod.SomeAnnoyingItem")
-- DFBanBox.ban("AnotherMod.AnotherItem")

-- ---------------------------------------------------------------------------
-- Copyright (C) 2026 Project_Omen. Part of Requiem of the Dead.
--
-- Free software under the GNU General Public License, version 3 or later.
-- You may use, study, modify and share it. If you share it - modified or not,
-- on the Workshop or anywhere else - keep this notice, license your version
-- under the GPL too, publish your source, and say what you changed.
-- Distributed in the hope it is useful, but WITHOUT ANY WARRANTY.
-- <https://www.gnu.org/licenses/gpl-3.0.html>
